- Cargo.lock
- execution/Cargo.toml
- execution/src/api.rs
- execution/src/env.rs
- execution/src/execution_impl.rs
- execution/src/lib.rs
- execution/src/types.rs
- src/main.rs
- src/tests.rs
- extends the env of wasmer-as
- add metering with wasmer
- fix the main temporary
> Implement metering

- src/execution_impl.rs
> Call module return result.

- src/env.rs
- src/execution_impl.rs
- wasm/assembly/massa.ts
> Rename how many.

- wasm/assembly/massa.ts
> Remove duplicate identifier.

- src/abi_impl.rs
- src/execution_impl.rs
- src/settings.rs
- src/types.rs
Fix #40
Sc runtime has move quite a bit during my vacation so I may missing a spot. Also I need help on tagging this properly.
> Add generate event in interface.

- src/abi_impl.rs
- src/execution_impl.rs
- src/settings.rs
- src/types.rs
> Add transfer abi

- src/abi_impl.rs
- src/execution_impl.rs
- src/settings.rs
- src/tests.rs
- src/types.rs
> ABI: add get_balance

- src/abi_impl.rs
- src/execution_impl.rs
- src/tests.rs
- src/types.rs
- wasm/assembly/massa.ts
Uniformize names, add missing functions to massa.ts
> update names and tooling

- .github/workflows/ci.yml
If you see this commit in a few weeks, revert it quick.
> Temporary pin CI nightly version

- Cargo.lock
> Update missed cargo lock

- src/execution_impl.rs
- src/tests.rs
Just add a closure in order to be able to wrap the Runtime error and replace it with a better named error.
*Doesn't breaks the api*
I followed the wasmer [example here](https://github.com/wasmerio/wasmer/blob/master/examples/metering.rs)
> Better handling for an Out Of Gas error

- src/abi_impl.rs
- src/execution_impl.rs
- src/settings.rs
- src/tests.rs
- src/types.rs
- wasm/README.md
- wasm/assembly/caller.ts
- wasm/assembly/local_hello_name_caller.ts
- wasm/assembly/massa.ts
- wasm/build/caller.wat
- wasm/build/local_hello_name_caller.wat
Part of https://github.com/massalabs/massa/issues/2154
> Add call coins

- .gitignore
- src/abi_impl.rs
- src/tests.rs
- src/types.rs
Fix #28 High-level interface :sunglasses: how do we pass whatever Rust type we want to AssemblyScript
> Developer experience: take advantage of `serde_json` for easier ABI definitions (and better SDK)

- src/execution_impl.rs
Not sure what's the right moment to merge this one? (in intend to have a _smooth_ transition)
> Remove outdated imports (keeped for retrocompatibility)

- src/abi_impl.rs
- src/execution_impl.rs
- src/lib.rs
- src/settings.rs
- src/tests.rs
- src/types.rs
https://github.com/massalabs/massa-sc-runtime/issues/110
> 110 implement async calls

- src/abi_impl.rs
- src/execution_impl.rs
- src/settings.rs
- src/tests.rs
- src/types.rs
Add ABIs to set the bytecode of an address
> add set bytecode

- Cargo.toml
- src/execution/mod.rs
Close https://github.com/massalabs/massa-sc-runtime/issues/165
> Add check out of gas initialization.

- Cargo.lock
- Cargo.toml
Context : https://github.com/chronotope/chrono/issues/602
> Fix chrono security issue.

- Cargo.lock
- Cargo.toml
- src/as_execution/abi.rs
- src/tests/mod.rs
- src/types.rs
Fix #233 . The PR on massa will follow.
> Update hash to take bytes and not string.

- src/as_execution/abi.rs
- src/as_execution/context.rs
- src/types.rs
Related issue: #142 
Related PR in massa: https://github.com/massalabs/massa/pull/3645
Add a new ABI to validate if an address is correct
> Add a new address validation ABI

- src/as_execution/abi.rs
- src/as_execution/context.rs
- src/types.rs
Related issue: https://github.com/massalabs/massa/issues/3625
New ABI to get all the keys in a datastore matching a given prefix
> Implement new ABI "get_matching_key_for"

- Cargo.lock
- Cargo.toml
- src/tests/mod.rs
- src/tunable_memory.rs
> improve dependency

- src/wasmv1_execution/abi/abis.rs
- src/wasmv1_execution/abi/helper_traits.rs
Signed-off-by: Jean-François Morcillo <jfm@massa.net>
> Adjust macro resp_ok resp_err, clean abis function_exists and transfer_coins

- Cargo.lock
- Cargo.toml
- src/tests/mod.rs
- src/tests/tests_runtime.rs
- src/types.rs
- src/wasmv1_execution/abi/abis.rs
The main changes are described here: https://github.com/massalabs/massa-proto/pull/19
> Various ABI updates (updated protos)

- src/as_execution/context.rs
- src/lib.rs
Part of https://github.com/massalabs/massa/issues/1100
> Make sc-runtime stable compliant.

- src/wasmv1_execution/abi/handler.rs
- src/wasmv1_execution/env.rs
- src/wasmv1_execution/ffi.rs
- src/wasmv1_execution/mod.rs
Add deallocation of data (if `__dealloc` is exported by guest)
> add deallocation

- .github/workflows/ci.yml
- Cargo.lock
- build.rs
- rust-toolchain.toml
- rustfmt.toml
- src/as_execution/abi.rs
- src/as_execution/common.rs
- src/as_execution/context.rs
- src/as_execution/env.rs
- src/as_execution/mod.rs
- src/execution.rs
- src/middlewares/dumper.rs
- src/middlewares/gas_calibration.rs
- src/tests/mod.rs
- src/tests/tests_gas_calibration.rs
- src/tests/tests_runtime.rs
- src/tunable_memory.rs
- src/types.rs
- src/wasmv1_execution/abi/abis.rs
- src/wasmv1_execution/abi/handler.rs
- src/wasmv1_execution/env.rs
- src/wasmv1_execution/ffi.rs
- src/wasmv1_execution/mod.rs
This PR has a lot of changes because it removes style rules that are only on nightly and also a cargo update. But the goal is just to use 1.72 eveywhere
> update runtime toolchain

- Cargo.lock
- src/as_execution/common.rs
> Add context to error messages 'Provided gas...'

- licenses/Apache 2.0.txt
- licenses/MIT.txt
Cf https://github.com/massalabs/massa/issues/4636
> Add licenses
